version: '3'

services:

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - test

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - test


networks:
  test:
    driver: bridge